### PR TITLE
Implement basic support for pdfpc

### LINKED ISSUE #52: Speaker notes
First of all, amazing project (or [a package](https://github.com/typst/typst/commit/7b92bd7c340d9f9c094ed2fa57912049317d9b20)?) which I used for my PhD proposal presentation.

I wanted to start a discussion around speaker notes and how to implement it and which features it should contain (happy to help out).
It seems natural that `speaker-notes` would be a named argument to `slide` and that there would be a global switch: `#show: slides.with( /* ... */, notes: true )` which would print them out, likely underneath the slide (this would mean changing the aspect ratio etc).

Currently I have the notes on separate slides with custom theme variant which are turned off based on a state:
```
#let notes(body) = {
  locate(loc => {
    if notes-mode.at(loc) {
        slide(theme-variant: "notes", body)
    } 
  })
}
```

### PR DESCRIPTION
**Pull request by andreasKroepelin**
This allows the pdfpc presentation tool to correctly understand slides produced by polylux.
So far, overlay detection and speaker notes are implemented.

Fixes #52 

Pinging @zouharvi and @JuliusFreudenberger, you might be interested in this :)

### CODE REVIEW

**Comment by JuliusFreudenberger** [comment]
@andreasKroepelin, this is wonderful. I'm giving a presentation the next monday so this comes at a really nice time!
I tried this new feature and adding notes to the presentation works quite well.

The steps I did are the following (for others to try):
1. Clone the project and switch to the branch `pdfpc`
2. Copy the presentation files into the project and change the reference of `@preview/polylux:0.2.0` to `polylux.typ`
3. Add a note to a slide by using the new `note` function as shown in [the example](https://github.com/andreasKroepelin/polylux/pull/73/files#diff-c8198c452fb2d016cde4cf6bc4fa75fbc943ad3d35481bae41cadd988b4219c4)
4. Compile the `pdfpc-extractor` by executing `cargo build` in the directory `pdfpc-extractor`
5. Execute `pdfpc-extractor <presentation-file>.typ
6. Build the slides pdf
7. Open the pdf with pdfpc, the *.pdfpc file generated by `pdfpc-extractor` next to it will be used.
8. Notes are shown

One thing that I am missing are the general options that can be set in `latex-pdfpc`.
These are `duration` (or `startTime` and `endTime`) and `lastMinutes`.
An example for these settings can be seen [here](https://github.com/pdfpc/latex-pdfpc/blob/773c3e9c74fa73e8683edb852c177469993a0451/pdfpc/README.md?plain=1#L43-L44).
These attributes are added in the JSON-structure next to `pdfpcFormat`.

**Comment by andreasKroepelin** [comment]
Thanks for the feedback and the short "tutorial"! I will add more pdfpc config options later.

**Comment by JuliusFreudenberger** [comment]
That is fine for me. I'm very happy, that I won't have to add the notes in pdfpc directly (which made it a bit cumbersome to add a slide after creating the notes as I had to manually shift the slide indices in the JSON). 
Adding the duration manually while setting the notes in the source file is fine for now.

**Comment by andreasKroepelin** [comment]
@JuliusFreudenberger I added a bunch of config options 😎 Detailed documentation will follow before I publish the next release of this package.

**Comment by JuliusFreudenberger** [comment]
Very cool, I'm really looking forward to testing this.
When will you release the next version?

I created an [AUR package for polylux2pdfpc](https://aur.archlinux.org/packages/polylux2pdfpc-git) which always tracks the HEAD of main.
This allows easy installation on Arch Linux and its derivatives.

**Comment by andreasKroepelin** [comment]
> When will you release the next version?

Soon :D So there are a couple of features for overlays that I want to add. And some documentation.


> I created an [AUR package for polylux2pdfpc](https://aur.archlinux.org/packages/polylux2pdfpc-git) which always tracks the HEAD of main.

Awesome, thank you!

**Comment by drupol** [comment]
I'm testing `polylux2pdfpc` with Nix and it works. However, no notes are displayed in `pdfpc`.

I've been testing the core examples as well, and absolutely no notes are being displayed.

Am I missing something?

**Comment by drupol** [comment]
False alert, I think the problem only comes from Ubuntu, I cannot reproduce the issue on NixOS.

I'll dig a bit more on Monday.

**Pull request merged**
